create table consent (id bigint not null auto_increment, consent_reference_id varchar(255) not null, consent_stage varchar(255) not null, end_date datetime, saved_pdf longblob, start_date datetime, patient_id bigint, primary key (id)) ENGINE=InnoDB;
create table consent_attestation_aud (id bigint not null, rev integer not null, revtype tinyint, consent_attestation_pdf longblob, fhir_consent longblob, consent_id bigint, consent_attestation_term_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table consent_attestation_term_aud (id bigint not null, rev integer not null, revtype tinyint, text varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table consent_aud (id bigint not null, rev integer not null, revtype tinyint, consent_reference_id varchar(255), consent_stage varchar(255), end_date datetime, saved_pdf longblob, start_date datetime, patient_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table consent_from_providers_aud (rev integer not null, consent_id bigint not null, from_providers_id bigint not null, revtype tinyint, primary key (rev, consent_id, from_providers_id)) ENGINE=InnoDB;
create table consent_from_providers (consent_id bigint not null, from_providers_id bigint not null) ENGINE=InnoDB;
create table consent_revocation_aud (id bigint not null, rev integer not null, revtype tinyint, consent_revocation_pdf longblob, consent_id bigint, consent_revocation_term_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table consent_revocation_term_aud (id bigint not null, rev integer not null, revtype tinyint, text varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table consent_share_purposes_aud (rev integer not null, consent_id bigint not null, share_purposes_id bigint not null, revtype tinyint, primary key (rev, consent_id, share_purposes_id)) ENGINE=InnoDB;
create table consent_share_sensitivity_categories_aud (rev integer not null, consent_id bigint not null, share_sensitivity_categories_id bigint not null, revtype tinyint, primary key (rev, consent_id, share_sensitivity_categories_id)) ENGINE=InnoDB;
create table consent_share_purposes (consent_id bigint not null, share_purposes_id bigint not null) ENGINE=InnoDB;
create table consent_share_sensitivity_categories (consent_id bigint not null, share_sensitivity_categories_id bigint not null) ENGINE=InnoDB;
create table consent_to_providers_aud (rev integer not null, consent_id bigint not null, to_providers_id bigint not null, revtype tinyint, primary key (rev, consent_id, to_providers_id)) ENGINE=InnoDB;
create table consent_to_providers (consent_id bigint not null, to_providers_id bigint not null) ENGINE=InnoDB;
create table consent_attestation (id bigint not null auto_increment, consent_attestation_pdf longblob, fhir_consent longblob, consent_id bigint not null, consent_attestation_term_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table consent_attestation_term (id bigint not null auto_increment, text varchar(20000) not null, primary key (id)) ENGINE=InnoDB;
create table consent_revocation (id bigint not null auto_increment, consent_revocation_pdf longblob, consent_id bigint not null, consent_revocation_term_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table consent_revocation_term (id bigint not null auto_increment, text varchar(20000) not null, primary key (id)) ENGINE=InnoDB;
create table organization (id bigint not null auto_increment, city varchar(255), country varchar(255), line1 varchar(255), line2 varchar(255), postal_code varchar(255), state varchar(255), name varchar(255) not null, phone_number varchar(255), consent_attestation_id bigint not null, provider_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table organization_aud (id bigint not null, rev integer not null, revtype tinyint, city varchar(255), country varchar(255), line1 varchar(255), line2 varchar(255), postal_code varchar(255), state varchar(255), name varchar(255), phone_number varchar(255), consent_attestation_id bigint, provider_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table patient (id bigint not null, primary key (id)) ENGINE=InnoDB;
create table patient_aud (id bigint not null, rev integer not null, revtype tinyint, primary key (id, rev)) ENGINE=InnoDB;
create table patient_providers (patient_id bigint not null, providers_id bigint not null) ENGINE=InnoDB;
create table practitioner (id bigint not null auto_increment, city varchar(255), country varchar(255), line1 varchar(255), line2 varchar(255), postal_code varchar(255), state varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, middle_name varchar(255), phone_number varchar(255), consent_attestation_id bigint not null, provider_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table practitioner_aud (id bigint not null, rev integer not null, revtype tinyint, city varchar(255), country varchar(255), line1 varchar(255), line2 varchar(255), postal_code varchar(255), state varchar(255), first_name varchar(255), last_name varchar(255), middle_name varchar(255), phone_number varchar(255), consent_attestation_id bigint, provider_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table provider (id bigint not null auto_increment, system varchar(255), value varchar(255), primary key (id)) ENGINE=InnoDB;
create table provider_aud (id bigint not null, rev integer not null, revtype tinyint, system varchar(255), value varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table purpose (id bigint not null auto_increment, description varchar(255), display varchar(255), system varchar(255), value varchar(255), primary key (id)) ENGINE=InnoDB;
create table purpose_aud (id bigint not null, rev integer not null, revtype tinyint, description varchar(255), display varchar(255), system varchar(255), value varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) ENGINE=InnoDB;
create table sensitivity_category_aud (id bigint not null, rev integer not null, revtype tinyint, description varchar(5000), display varchar(255), system varchar(255), value varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table sensitivity_category (id bigint not null auto_increment, description varchar(5000), display varchar(255), system varchar(255), value varchar(255), primary key (id)) ENGINE=InnoDB;
alter table provider add constraint provider_identifier_idx unique (system, value);
alter table purpose add constraint purpose_identifier_idx unique (system, value);
alter table sensitivity_category add constraint sensitivity_category_identifier_idx unique (system, value);
alter table consent add constraint FK975ajb9rne9852qoi9c2rq2pg foreign key (patient_id) references patient (id);
alter table consent_attestation_aud add constraint FKphkfmuj1jkjatxnccrhhjy9a3 foreign key (rev) references revinfo (rev);
alter table consent_attestation_term_aud add constraint FKpm4bkdkb9y5j5orswctcs2wt6 foreign key (rev) references revinfo (rev);
alter table consent_aud add constraint FKrivjdr7b84vfpylp6bpakhsu8 foreign key (rev) references revinfo (rev);
alter table consent_from_providers_aud add constraint FKckyhc1yyppfspmgebf5l77blu foreign key (rev) references revinfo (rev);
alter table consent_from_providers add constraint FKlwjxq6n33ii2oq7scqgnqn66w foreign key (from_providers_id) references provider (id);
alter table consent_from_providers add constraint FKtbyyroo1u1wtkaphub0x7may4 foreign key (consent_id) references consent (id);
alter table consent_revocation_aud add constraint FKeqrekl624qhx5tg2eeyyhqdc9 foreign key (rev) references revinfo (rev);
alter table consent_revocation_term_aud add constraint FKgkmqy64g4efq6ace6io70ryji foreign key (rev) references revinfo (rev);
alter table consent_share_purposes_aud add constraint FK7ldl41gkbp0i79icwy28r2k11 foreign key (rev) references revinfo (rev);
alter table consent_share_sensitivity_categories_aud add constraint FKgaot3nxa3niwehu5bv3pmn273 foreign key (rev) references revinfo (rev);
alter table consent_share_purposes add constraint FK88abfnnknv1tnuf20s7qlakqi foreign key (share_purposes_id) references purpose (id);
alter table consent_share_purposes add constraint FKqkkoytykbvwn9mypwlxifbdsy foreign key (consent_id) references consent (id);
alter table consent_share_sensitivity_categories add constraint FK3mcrw8uh9bvk2yiuaq7vrf48p foreign key (share_sensitivity_categories_id) references sensitivity_category (id);
alter table consent_share_sensitivity_categories add constraint FKb535hudvq3stprmhxtsc1foq7 foreign key (consent_id) references consent (id);
alter table consent_to_providers_aud add constraint FK90xsn53xvmsc44epvybhl03js foreign key (rev) references revinfo (rev);
alter table consent_to_providers add constraint FKro16gtspsorvj1ekhih378hmn foreign key (to_providers_id) references provider (id);
alter table consent_to_providers add constraint FKam4kc2hc8lirjaoid03m6as99 foreign key (consent_id) references consent (id);
alter table consent_attestation add constraint FKmapieuhcqbvymymwwwl803e9j foreign key (consent_id) references consent (id);
alter table consent_attestation add constraint FKkhx38dvxi4u6175kf8rs7qmqi foreign key (consent_attestation_term_id) references consent_attestation_term (id);
alter table consent_revocation add constraint FKsdlgov269t0m90lfguq31hlly foreign key (consent_id) references consent (id);
alter table consent_revocation add constraint FKgj967ixvjwd9mpcdnwh9wkfjd foreign key (consent_revocation_term_id) references consent_revocation_term (id);
alter table organization add constraint FK9jug41w1xluibkpq2a5m4pc8v foreign key (consent_attestation_id) references consent_attestation (id);
alter table organization add constraint FKhjr6fnurix16mb0ijxnx5j9 foreign key (provider_id) references provider (id);
alter table organization_aud add constraint FKjc7pc3ombplinmhjykfmu9ckg foreign key (rev) references revinfo (rev);
alter table patient_aud add constraint FKauc2cjb3q09bv9n4ypk4rlj8s foreign key (rev) references revinfo (rev);
alter table patient_providers add constraint FKoq01y20kaluh6ah1ojlpq0phg foreign key (providers_id) references provider (id);
alter table patient_providers add constraint FK9yk8mkbajtynqjk49xe1abqm2 foreign key (patient_id) references patient (id);
alter table practitioner add constraint FKseu8ofhvw5hvnf4wh6nubvnk9 foreign key (consent_attestation_id) references consent_attestation (id);
alter table practitioner add constraint FKe0w6snxjd8hyb2kuwci4g2ycx foreign key (provider_id) references provider (id);
alter table practitioner_aud add constraint FK4dvwvqjs5js2ur8fkysmq4f45 foreign key (rev) references revinfo (rev);
alter table provider_aud add constraint FKdeawbj4t86llkuum8862256hg foreign key (rev) references revinfo (rev);
alter table purpose_aud add constraint FK9jyp24j6vswcp8rkeeg5q6lmh foreign key (rev) references revinfo (rev);
alter table sensitivity_category_aud add constraint FK2icubaolwxt4t0nuq25qwt15q foreign key (rev) references revinfo (rev);